extends: standard
rules: &rules
  curly: [error, multi]
  import/no-default-export: error
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: [block-like, if]
      next: '*'
    - blankLine: always
      prev: '*'
      next: [block-like, if]
    - blankLine: always
      prev: [const, let]
      next: [expression, for]
    - blankLine: always
      prev: expression
      next: [const, let]
    - blankLine: always
      prev: [multiline-const, multiline-let]
      next: '*'
    - blankLine: always
      prev: '*'
      next: [multiline-const, multiline-let]
overrides:
  - files: ['*.ts']
    extends: standard-with-typescript
    rules:
      <<: *rules
      '@typescript-eslint/no-non-null-assertion': off
      '@typescript-eslint/promise-function-async': off
